### PR TITLE
Create script for feathering all arrays

### PR DESCRIPTION
**Pull request by d-l-walker**
- Added the script `aces/joint_deconvolution/feather_all.py` to perform full 12M + 7M + TP feathering for all regions for a given SPW.
- Added table `aces/data/tables/aces_SB_uids.csv` in order to more easily grab the relevant directories for each uid.

### CODE REVIEW

**Comment by d-l-walker** [comment]
Still to be done:
- Have someone review code and method
- Implement primary-beam correction post-feathering
- Add code to clean up unnecessary intermediary files
- Add fixes to satisfy code style checks

**Comment by d-l-walker** [comment]
There are still lots of errors due to flake8 not knowing about the various CASA tasks. (`F821 undefined name`). 
Possible simple solutions are to add `# flake8: noqa` to script, or add an explicit exception to `tox.ini` -- @keflavich, any preference?

**Comment by keflavich** [comment]
You'll likely need to add lines to `tox.ini` to ignore style suggestions - look at the last few lines of that file for examples.

**Comment by d-l-walker** [comment]
@keflavich no need to add any exceptions to `tox.ini`. The `casatasks` import was the only outstanding issue.

I still have some updates planned to improve the code and add functionality, but this can now be merged in the meantime.

**Review by keflavich — APPROVED** [review]

**Pull request merged**
