### PR TITLE
Added cube cleaning params for Sgr_A_st_al_03_TM1 (#126)

### PR DESCRIPTION
**Pull request by d-l-walker**
I've added the cube imaging parameters for Sgr_A_st_al_03_TM1. These were previously not present at all as this region was manually imaged during QA2.

### CODE REVIEW

**Comment by d-l-walker** [comment]
Hmm. The checks have failed. Is this because `Sgr_A_st_al_03_TM1` was not present in `default_tclean_commands.json` in the first place? Do we need to add a template in that file in order to merge with the over-ride commands?

**Comment by keflavich** [comment]
Yes, that's why, but no, `default_tclean_commands` cannot be edited.  I need to work around this.

**Comment by keflavich** [comment]
rebase this & it should now work

**Review by keflavich — APPROVED** [review]
@d-l-walker this looks fine, but in the future, I suggest leaving out the parameters that don't need to be specified - i.e., any that are correct in the default parameters.  This should include `intent`, `datacolumn`, `stokes`, etc.  `override_tclean` should really only have the things that are *different* from `default`.

**Pull request merged**
