### PR TITLE
Undo size mitigation for #150

### PR DESCRIPTION
**Pull request by d-l-walker**
Updated channel parameters for #150 (Sgr_A_st_b_TM1). SPW 33 is fine, this is for all other SPWs.

### CODE REVIEW

**Comment by d-l-walker** [comment]
Hmm, this seems to have failed the code style checks but I'm not sure why. All of the errors appear to relate to other scripts. I'll look into it ...

**Comment by keflavich** [comment]
Rebase against main (`git pull upstream main --rebase`, assuming you have the remote repo labeled upstream) and see if that fixes the codestyle.

**Comment by d-l-walker** [comment]
Hmm, still seems to be failing for the same reason. Looking at your latest PR (#391) I see many similar errors. Has something changed with the code style rules? Or am I just doing something stupid?

**Comment by keflavich** [comment]
strange, I run tox locally successfully
```
tox -e codestyle
codestyle installed: flake8==6.1.0,mccabe==0.7.0,pycodestyle==2.11.1,pyflakes==3.1.0
codestyle run-test-pre: PYTHONHASHSEED='234886569'
codestyle run-test: commands[0] | flake8 aces --count --max-line-length=200 --ignore=W504,E265,F401,W292
0
```

**Pull request merged**
