### PR TITLE
Shift planning

### PR DESCRIPTION
**Pull request by keflavich**
Based on the regions Ash made, I added a script to check what the peak intensity would be in each region with a given set of shifts.

This is what we miss before correcting:
peak_missed_hcop_noshift_regcontours

These show what happens if we use the corrections included in this PR:
peak_missed_hcop_regcontours

### CODE REVIEW

**Comment by ashleythomasbarnes** [comment]
This is HCO+ with the velocity shifts that I suggested - or those that you have updated (to some more with +40kms)? Could you also make this for HNCO? I suspect this won't show much interesting (checking the channel maps the HCO+ is far more extended).

**Comment by keflavich** [comment]
this includes the additional changes (a few more fields, plus some additional +10 km/s shifts).  I did this originally with the version you made, and there were some features that stuck out, so I tried more shifting

**Comment by keflavich** [comment]
and yeah easy enough to do this w/hnco - you can also try it out if you have the MOPRA data handy

**Comment by keflavich** [comment]
HNCO version.  The one that looks good is after shifting.

with shift:
peak_missed_hnco_regcontours

no shift:
peak_missed_hnco_noshift_regcontours

**Comment by ashleythomasbarnes** [comment]
Okay good, looks like there is still some very low level emission that we may be missing (also some towards Sgr A*), but as the HNCO is clean I'm pretty happy with these velocity shifts

**Comment by ashleythomasbarnes** [comment]
That leaves the following issue of the already observed field with (HCO+) emission outside of the velocity range 

[https://github.com/ACES-CMZ/reduction_ACES/issues/3](url)

**Comment by ashleythomasbarnes** [comment]
As HNCO is okay here, I don't _think_ its worth updating

**Comment by keflavich** [comment]
yes, agreed - I think the SgrA is just not solvable, b/c it's wider on both ends.

Agree also about Issue #3 - I think we need to ask for it to be reobserved if ALMA will let us

**Comment by ashleythomasbarnes** [comment]
You think we should re-observe? I'm not sure, looking at your first figure, even if we change the velocity ranges I feel there that there are still going to be several similar cases for the HCO+ - where emission is on the edge of the band.

**Comment by ashleythomasbarnes** [comment]
If we can't solve the HCO+ within +-100km, one option would be to smooth to 0.4kms (only the HCO+) and get +-200km

**Pull request merged**
